#!/bin/sh
# <!-- **************************************  -->
# <!-- Don't Remove this Disclaimer            -->
# <!-- **************************************  -->
EXTDIR="/usr/lib/enigma2/python/Plugins/Extensions/revolution/"
if [ -d "$EXTDIR" ]; then
   rm -rf "$EXTDIR" > /dev/null 2>&1
fi
echo "***********************************"
echo "* Proceeding to installation...   *"
echo "***********************************"
cd /
exit 0
